[package]
name = "fluxion"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
futures-util = "0.3.31"
stream-utils = "0.2.0"
pin-project = "1.1.0"
tokio = { version = "1.47.1", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
tokio-util = "0.7"
async-trait = "0.1.68"
async-stream = "0.3"
shared_stream = "0.2"
futures-stream-select-all = "0.1"
futures-stream-select-all-send = "0.1.2"

[dev-dependencies]
rstest = "0.26.1"