[build]
timeout = "120s"

[report]
engine = "Llvm"
out = ["Html", "Xml"]

[run]
fail-under = 85
exclude-files = [
  "examples/**",
  "*/tests/async_std/**",
  "*/tests/embassy/**",
  "*/tests/smol/**",
  "*/tests/wasm/**",
]

