[build]
timeout = "120s"

[report]
engine = "Llvm"
out = ["Html", "Xml"]

[run]
fail-under = 80
workspace = true
exclude-tests = true
exclude-files = [
  "**/examples/**",
  "**/tests/async-std/**",
  "**/tests/smol/**",
  "**/tests/wasm/**",
  "**/tests/embassy/**",
  "**/tests/**/helpers.rs",
]


