[build]
timeout = "120s"

[report]
engine = "Llvm"
out = ["Html", "Xml"]

[run]
fail-under = 88
exclude-files = [
  "examples/**",
  "fluxion-stream-time/tests/wasm/**",
  "fluxion-stream-time/tests/async_std/**"
]
