[build]
timeout = "120s"

[report]
engine = "Llvm"
out = ["Html", "Xml"]

[run]
fail-under = 85
exclude-files = [
  "examples/**",
  "*/tests/**",
  "**/tests/**",
  "fluxion-stream-time/tests/**",
  "fluxion-test-utils/src/**",
]

